### ISSUE TITLE
Signal color goes off

### ISSUE THREAD

**Issue by MichaelSchroter** [ghostbsd/networkmgr#59] opened 2021-05-07 04:11 UTC
Hi I have installed `networkmgr` on FreeBSD 13 using `pkg install networkmgr`. However, I have a small issue with it. While, the signal strength indicator default color is blue sometimes it becomes ash color. This happens around 50% of the time. Furthermore, it happens when I start the computer and stays like that for the duration. This issue does not have an effect on the internet performance.
Please let me know if I could do anything about it. Please find the attached [image](https://drive.google.com/file/d/1PDiTiayU0AUA2wNx3SZ1RzyRL_s6SLb2/view?usp=sharing) of it.

Thanks & Best Regards

Michael

**Comment by ericbsd** [comment] 2021-09-11 20:09
I know this report is old but I was wondering if the driver was iwm?

**Comment by ericbsd** [comment] 2021-09-11 20:11
I have one laptop that I can reproduce it with, but it looks like the iwm driver is at fault.

**Comment by MichaelSchroter** [comment] 2021-09-12 06:12
Hi,

Thanks for the reply. Yes. I believe so. My laptop is ideapad 100S-14IBR.
So how can I overcome this issue? I have currently installed `wifimgr`
through pkg.

Thanks & Best Regards

Schroter

**Comment by ericbsd** [comment] 2021-09-12 16:47
I have tested wifimgr and I see the same problem then NetworkMgr. The ways the signal is calculated is the same in NetworkMgr then wifimgr. So you should see the same problem with it.

**Comment by MichaelSchroter** [comment] 2021-09-12 23:34
Hi, thanks for the reply. In my case there is a small issue when the
connection goes down where, the WiFi still shows it is connected. That is
the only issue I have come across so far. The loss of blue colour in the
WiFi signal icon does not happen in Wifimgr for me.

Are there any plans to solve these issues please?

Thanks & Best Regards

Schroter

**Comment by MichaelSchroter** [comment] 2021-09-12 23:48
Hi, thanks for the reply. In my case there is a small issue (in ```wifimgr```) when the
connection goes down where, the WiFi still shows it is connected. Also, the GUI of ```wifimgr``` is also a bit off (please see FreeBSD image and wifi up-down button). Please refer the attached [image](https://drive.google.com/file/d/14TP8UEpNUMl8ll_mhLGKoj5JBwViDllM/view?usp=sharing) of it for our kind perusal. Those are the only issues I have come across so far. The loss of blue color in the
WiFi signal icon does not happen in ```wifimgr``` (as in ```networkmgr```) for me.

Are there any plans to solve these issues please?

Thanks & Best Regards

Schroter

**Comment by ericbsd** [comment] 2021-09-13 11:41
I think the issue is at the driver level and not with wifimgr and NetworkMgr. Can you give me the output off this `ifconfig wlan0 | grep "parent interface"`? So far, I have tested 4 drivers, and only iwm give me those results.

**Comment by MichaelSchroter** [comment] 2021-09-13 13:48
> I think the issue is at the driver level and not with wifimgr and NetworkMgr. Can you give me the output off this `ifconfig wlan0 | grep "parent interface"`? So far, I have tested 4 drivers, and only iwm give me those results.

Hi, thanks for the reply. I get: `parent interface: iwm0`
Thanks & Best Regards
Schroter

**Comment by ericbsd** [comment] 2021-11-04 11:43
iwm is an incomplete driver, it does not support AC and I will not be able to fix this issue since I am not a kernel module and driver developer.

I am closing this issue.

**Closed** 2021-11-04 11:44 UTC
Labels: bug
